<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Pidge.Protocol</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pidge.Codegen\Pidge.Codegen.csproj" />
    <ProjectReference Include="..\Pidge.Core\Pidge.Core.csproj" />
    <ProjectReference Include="..\Pidge.Storage\Pidge.Storage.csproj" />
  </ItemGroup>

</Project>
