<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Pidge.HttpEngine.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pidge.HttpEngine\Pidge.HttpEngine.csproj" />
    <ProjectReference Include="..\..\tests\Pidge.TestServer\Pidge.TestServer.csproj" />
  </ItemGroup>

</Project>
