import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { Plugin } from "vite";

/**
 * Ships the bundled fonts' licences with the bundled fonts.
 *
 * Inter and JetBrains Mono are both SIL Open Font License 1.1, which requires
 * the licence to travel with the font. The fonts are emitted by Vite as build
 * assets, so their licences are emitted the same way rather than left behind in
 * the source tree for a packager to remember.
 *
 * One source of truth: the files next to the woff2 in `packages/ui/src/fonts`.
 */

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = join(repoRoot, "packages", "ui", "src", "fonts");

const LICENCE_FILES = ["Inter-LICENSE.txt", "JetBrainsMono-LICENSE.txt"] as const;
const NOTICE_FILE = "THIRD-PARTY-LICENSES.md";

export interface FontLicenseOptions {
  /** Directory inside the build output. */
  outDir?: string;
  /**
   * An extra directory on disk to copy the same files into, for bundlers that
   * read from the filesystem rather than from the build output. The desktop app
   * uses this so Tauri can list them under `bundle.resources`.
   */
  copyTo?: string;
}

export function fontLicenses({ outDir = "licenses", copyTo }: FontLicenseOptions = {}): Plugin {
  const sources = [
    ...LICENCE_FILES.map((name) => ({ name, path: join(fontDir, name) })),
    { name: NOTICE_FILE, path: join(repoRoot, NOTICE_FILE) },
  ];

  return {
    name: "api-client:font-licenses",
    apply: "build",

    generateBundle() {
      for (const source of sources) {
        this.emitFile({
          type: "asset",
          fileName: `${outDir}/${source.name}`,
          source: readFileSync(source.path, "utf8"),
        });
      }
    },

    closeBundle() {
      if (!copyTo) return;
      mkdirSync(copyTo, { recursive: true });
      for (const source of sources) {
        copyFileSync(source.path, join(copyTo, source.name));
      }
      // A note for anyone who finds the directory and wonders where it came from.
      writeFileSync(
        join(copyTo, "README.md"),
        "Generated by `scripts/viteFontLicenses.ts` during the frontend build.\n" +
          "Edit the originals in `packages/ui/src/fonts/`, not these copies.\n",
      );
    },
  };
}
