[package]
name = "api-client-codegen"
description = "Turns a request into code for another client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
api-client-core.workspace = true
api-client-http-engine.workspace = true
base64.workspace = true
percent-encoding.workspace = true
serde.workspace = true
ts-rs.workspace = true
